### ISSUE TITLE
Debian 10 seems to be supported

### ISSUE THREAD

**Issue by jarekherisz** [voxpupuli/puppet-bareos#101]
What is the approval procedure for support in new version of debian? I am using this module with debian version 10 and it works fine. May I created PR to chang it for:
```json
"operatingsystem_support": [
    {
      "operatingsystem": "Debian",
      "operatingsystemrelease": [
        "9", "10"
      ]
    },
```

**Comment by root-expert** [comment]
Hellow @jarekherisz, PRs are more than welcomed!

The first step is to add Debian 10 in the metadata.json.
Normally our CI would verify that everything runs correctly for Debian 10 but this module doesn't have acceptance test :(
If you are using this module in your environment and you know it works without problems on Debian 10 you can add it!
