### ISSUE TITLE
support Virtuozzolinux OS.name with facter 3.14.2

### ISSUE THREAD

**Issue by benibr** [voxpupuli/puppet-bareos#47]
With https://github.com/puppetlabs/facter/commit/d9c30e5b336ecb87a816edf6b127deeb7388be07 the `os.name` fact is no longer `RedHat` under Virtuozzo linux systems. Therefore Bareos failes on https://github.com/voxpupuli/puppet-bareos/blob/master/manifests/repository.pp#L47

**Comment by benibr** [comment]
Can anybody have a look at this? Would be a pain to work around this if it's not fixed upstream.

**Comment by igalic** [comment]
> With puppetlabs/facter@d9c30e5 the `os.name` fact is no longer `RedHat under Virtuozzo linux systems`.

Apparently, VirtuozzoLinux is a RHEL, but which `$location` should we use for the repo URL?

**Comment by traylenator** [comment]
@igalic the location is the merge #48

**Comment by benibr** [comment]
Since facter reported `RedHat` till the update, I would just contiune using the RHEL string in the location.

**Comment by benibr** [comment]
works, thanks!
